spring.application.name=doAn2026

# ??i c?ng k?t n?i t? 5432 thành 5433
spring.datasource.url=jdbc:postgresql://localhost:5433/msme_database?TimeZone=UTC
spring.datasource.username=postgres
spring.datasource.password=vh692004
spring.datasource.driver-class-name=org.postgresql.Driver

# C?u hình JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.timezone.storage=UTC
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.query.fail_on_pagination_underfetch=true

# C?u hình Security JWT
app.jwt.secret=Q2h1eWVuVmllbktpbmhEb2FuaFdvbkdyb3VwRG9BblBob25nS2hhbTIwMjZTaWV1QmFvTWF0XzI1Nl9iaXQ=
app.jwt.expiration-ms=86400000
app.jwt.refresh-expiration-ms=604800000

# OpenAPI / Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.try-it-out-enabled=true

# Redis configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000ms

# File upload configuration - kich thuoc toi da 50MB
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

app.sms.provider=mock
