import fs from "node:fs/promises";
import { SpreadsheetFile, Workbook } from "@oai/artifact-tool";

const outputDir = "D:/gitlap/doAnSummer2026/outputs/019ff5dc-080c-7230-b9b2-751838ad3212";
const outputPath = `${outputDir}/INTEGRATION_TEST_FULL_SYSTEM_FLOWS.xlsx`;
const previewDir = "D:/gitlap/doAnSummer2026/work/full_flow_previews";
const wb = Workbook.create();
const green = "#76933C", navy = "#000080", cyan = "#CCFFFF", white = "#FFFFFF", black = "#000000";
const p2 = n => String(n).padStart(2, "0");
const steps = (...items) => items.map((x, i) => `${i + 1}. ${x}`).join("\n");

const flows = [
  {id:1,sheet:"IT01-RegisterOTP",title:"Registration and OTP verification",req:"Redis OTP -> Account -> Customer Profile -> JWT",endpoint:"POST /api/auth/register",good:'phone = "0944433222"; otp = "482615"; password = "Clinic@123"',bad:'otp = "48261"',state:'redis.otpVerified["0944433222"] = false',role:'systemRole = "CUSTOMER"',duplicate:'account.phone.count = 1',dependency:'Redis connection = unavailable',entity:"Account and Profile"},
  {id:2,sheet:"IT02-LoginToken",title:"Login and token refresh",req:"Account -> Authentication -> Access Token -> Refresh Token",endpoint:"POST /api/auth/login",good:'phone = "0944433222"; password = "Clinic@123"',bad:'password = "Wrong@123"',state:'account.isActive = false',role:'systemRole = "CUSTOMER"',duplicate:'refreshToken.revoked = true',dependency:'token.expiresAt = "2026-08-11T10:00:00"',entity:"JWT token pair"},
  {id:3,sheet:"IT03-Profile",title:"Customer profile and insurance lookup",req:"Account -> Profile -> BHXH insurance service",endpoint:"PUT /api/v1/profiles/me",good:'fullName = "John Carter"; phone = "0944433222"; insuranceCode = "BH1234567890123"',bad:'phone = "123"',state:'profile.accountId = "ACC-2002"',role:'systemRole = "CUSTOMER"',duplicate:'email = "john.carter@example.com" already exists',dependency:'BHXH service = timeout',entity:"Customer Profile"},
  {id:4,sheet:"IT04-Appointment",title:"Appointment booking and check-in",req:"Profile -> Medical Service -> Appointment -> Customer Visit",endpoint:"POST /api/v1/appointments",good:'customerId = "CUS-1001"; serviceId = "SRV-GENERAL-01"; scheduledAt = "2026-08-13T09:00:00"',bad:'serviceId = "SRV-UNKNOWN"',state:'appointment.status = "CANCELLED"',role:'systemRole = "RECEPTIONIST"',duplicate:'same customer and scheduledAt count = 1',dependency:'availableSlot.count = 0',entity:"Appointment and CustomerVisit"},
  {id:5,sheet:"IT05-PaymentQueue",title:"Invoice payment and queue creation",req:"Invoice -> Transaction -> Queue Ticket",endpoint:"POST /api/v1/invoices/INV-1001/pay",good:'invoiceId = "INV-1001"; amount = 500000; paymentMethod = "CASH"',bad:'amount = 499999',state:'invoice.status = "PAID"',role:'systemRole = "RECEPTIONIST"',duplicate:'successfulTransaction.count = 1',dependency:'invoiceItem.count = 0',entity:"Transaction and QueueTicket"},
  {id:6,sheet:"IT06-QueueExam",title:"Queue calling and examination start",req:"Queue Ticket -> Customer Visit -> Vital Signs -> Medical Record",endpoint:"POST /api/v1/queue-tickets/QUE-1001/call",good:'queueTicketId = "QUE-1001"; departmentId = "DEP-GENERAL"',bad:'queueTicketId = "QUE-9999"',state:'queueTicket.status = "DONE"',role:'systemRole = "DOCTOR"',duplicate:'medicalRecord.count = 1',dependency:'customerVisit.status = "COMPLETED"',entity:"QueueTicket and MedicalRecord"},
  {id:7,sheet:"IT07-Examination",title:"Diagnosis and prescription",req:"Medical Record -> ICD-10 -> Prescription -> Medicine",endpoint:"PUT /api/doctor/examinations/MR-1001",good:'medicalRecordId = "MR-1001"; icd10Code = "J00"; medicineId = "MED-001"; quantity = 10',bad:'icd10Code = "ZZZ"',state:'medicalRecord.status = "COMPLETED"',role:'systemRole = "DOCTOR"',duplicate:'prescriptionItem medicineId = "MED-001" already exists',dependency:'medicine.isActive = false',entity:"MedicalRecord and Prescription"},
  {id:8,sheet:"IT08-TestOrder",title:"Clinical test ordering",req:"Medical Record -> Test Request -> Laboratory Queue",endpoint:"POST /api/v1/test-requests",good:'medicalRecordId = "MR-1001"; serviceId = "SRV-LAB-CBC"',bad:'serviceId = "SRV-UNKNOWN"',state:'medicalRecord.status = "COMPLETED"',role:'systemRole = "DOCTOR"',duplicate:'sameServiceRequest.count = 1',dependency:'laboratoryDepartment.status = "INACTIVE"',entity:"TestRequest and QueueTicket"},
  {id:9,sheet:"IT09-LabResult",title:"Laboratory result completion",req:"Test Request -> Test Result -> Queue Return -> Patient Journey",endpoint:"POST /api/v1/test-requests/TR-1001/result/complete",good:'testRequestId = "TR-1001"; conclusion = "CBC values within reference range"',bad:'testRequestId = "TR-9999"',state:'testRequest.status = "COMPLETED"',role:'systemRole = "TECHNICIAN"',duplicate:'completedResult.count = 1',dependency:'resultFile = "cbc-result.exe"',entity:"TestResult and QueueTicket"},
  {id:10,sheet:"IT10-CompleteFollowup",title:"Examination completion and follow-up",req:"Medical Record -> Visit -> Queue -> Follow-up Appointment",endpoint:"POST /api/v1/medical-records/MR-1001/complete",good:'medicalRecordId = "MR-1001"; followUpDate = "2026-08-20"',bad:'followUpDate = "2026-08-10"',state:'incompleteTestRequest.count = 1',role:'systemRole = "DOCTOR"',duplicate:'medicalRecord.status = "COMPLETED"',dependency:'customerVisit.status = "CANCELLED"',entity:"MedicalRecord, Visit, and Follow-up"},
  {id:11,sheet:"IT11-InsuranceTxn",title:"Insurance claim and patient payment",req:"BHXH -> Invoice -> Insurance Coverage -> Transaction",endpoint:"POST /api/v1/invoices/INV-1001/insurance",good:'insuranceCode = "BH1234567890123"; invoiceId = "INV-1001"; coveredAmount = 400000',bad:'insuranceCode = "BH0000000000000"',state:'insurance.status = "EXPIRED"',role:'systemRole = "RECEPTIONIST"',duplicate:'insuranceClaim.count = 1',dependency:'BHXH response.status = "UNAVAILABLE"',entity:"Invoice and Insurance Claim"},
  {id:12,sheet:"IT12-StaffSchedule",title:"Staff scheduling and attendance",req:"Staff -> Capability -> Schedule -> Attendance",endpoint:"POST /api/v1/schedules",good:'staffId = "STF-DOC-01"; startAt = "2026-08-13T08:00:00"; endAt = "2026-08-13T12:00:00"',bad:'endAt = "2026-08-13T07:00:00"',state:'staff.isActive = false',role:'systemRole = "CLINIC_MANAGER"',duplicate:'overlappingSchedule.count = 1',dependency:'capability.serviceId = "SRV-GENERAL-01" not found',entity:"StaffSchedule and Attendance"},
  {id:13,sheet:"IT13-AdminCatalog",title:"Administrative catalog management",req:"Department -> Medical Service -> Service Capability",endpoint:"POST /api/v1/medical-services",good:'serviceCode = "SRV-CARDIO-01"; serviceName = "Cardiology Consultation"; price = 500000',bad:'price = -1',state:'department.status = "INACTIVE"',role:'systemRole = "ADMIN"',duplicate:'serviceCode = "SRV-CARDIO-01" already exists',dependency:'serviceCategoryId = "CAT-9999"',entity:"MedicalService and Capability"},
  {id:14,sheet:"IT14-NotifyChat",title:"Notification and support chat",req:"Account -> Notification -> Chat Session -> Message",endpoint:"POST /api/v1/chat/CHAT-1001/messages/customer",good:'sessionId = "CHAT-1001"; message = "I need appointment support"',bad:'message = ""',state:'chatSession.status = "CLOSED"',role:'systemRole = "CUSTOMER"',duplicate:'clientMessageId = "MSG-1001" already exists',dependency:'WebSocket session = disconnected',entity:"ChatMessage and Notification"},
  {id:15,sheet:"IT15-JourneyReport",title:"Patient journey, report, and feedback",req:"Visit -> Queue -> Medical Record -> Invoice -> Dashboard Report",endpoint:"GET /api/v1/patient-journeys/VIS-1001",good:'visitId = "VIS-1001"; customerId = "CUS-1001"',bad:'visitId = "VIS-9999"',state:'visit.customerId = "CUS-2002"',role:'systemRole = "CLINIC_MANAGER"',duplicate:'feedback.count = 1',dependency:'dateFrom = "2026-08-31"; dateTo = "2026-08-01"',entity:"PatientJourney and Report"}
];

function casesFor(f) {
  const id = `IT${p2(f.id)}`;
  return [
    {group:"Successful flow",desc:`Complete ${f.title.toLowerCase()}`,proc:steps(`Prepare ${f.good}`,`Send ${f.endpoint}`,`Query the related database records`),expected:steps("HTTP status = 200 or 201",`${f.entity} records are created or updated once`,"Response IDs match the stored records"),pre:steps("Database and Redis are available",f.role,"Referenced records exist")},
    {group:"Successful flow",desc:"Read the integrated result after processing",proc:steps(`Complete case ${id}-001`,`Call the corresponding GET endpoint`,`Compare response data with the database`),expected:steps("HTTP status = 200","Response contains the new integrated data","No duplicate related record exists"),pre:steps(`${id}-001 completed successfully`,"Bearer access token is valid")},
    {group:"Validation and authorization",desc:"Reject invalid request data",proc:steps(`Prepare ${f.bad}`,`Send ${f.endpoint}`,"Check response and database"),expected:steps("HTTP status = 400 or 404","A validation or not-found error is returned","No related record is created or changed"),pre:steps("Application and database are available","Remaining referenced records are valid")},
    {group:"Validation and authorization",desc:"Reject a protected request without authorization",proc:steps("Set Authorization = null",`Send ${f.id <= 3 ? "GET /api/auth/me" : f.endpoint}`,"Check response and business records"),expected:steps("HTTP status = 401","The protected operation is rejected","Business records remain unchanged"),pre:steps("The selected endpoint requires authentication","Security context has no authenticated account")},
    {group:"State and integration integrity",desc:"Reject an invalid business state",proc:steps(`Prepare ${f.state}`,`Send ${f.endpoint}`,"Check all participating entities"),expected:steps("HTTP status = 400 or 409","The current state is preserved","No partial downstream update is committed"),pre:steps(f.state,"Authentication context satisfies the endpoint requirement")},
    {group:"State and integration integrity",desc:"Prevent duplicate or downstream-inconsistent processing",proc:steps(`Prepare ${f.duplicate}`,`Prepare ${f.dependency}`,`Send ${f.endpoint}`,"Check transaction rollback and record counts"),expected:steps("HTTP status = 400, 409, or 503","Existing records remain unchanged","No duplicate or orphan record is stored"),pre:steps(f.duplicate,f.dependency,"Database transaction management is enabled")}
  ];
}

const addSheet = name => { const s = wb.worksheets.add(name); s.showGridLines = true; return s; };
const border = {preset:"all",style:"thin",color:black};
const cover = addSheet("Cover"), list = addSheet("Test Cases"), stats = addSheet("Test Statistics");

cover.getRange("A2:F2").merge(); cover.getRange("A2").values=[["INTEGRATION TEST REPORT DOCUMENT"]];
cover.getRange("A2:F2").format={font:{name:"Arial",size:24,bold:true},horizontalAlignment:"center",verticalAlignment:"center",borders:border};
cover.getRange("A4:D7").values=[["Project Name","Clinic Management System","Created By","QA Team"],["Project Code","CLINIC","Issue Date",new Date("2026-08-12")],["Document Code","CLINIC_INTEGRATION_TEST","Version","1.0"],["Test Environment","Spring Boot; PostgreSQL; Redis; Postman/Swagger","Status","Ready for review"]];
cover.getRange("A4:D7").format={font:{name:"Arial",size:11},wrapText:true,borders:border}; cover.getRange("A4:A7").format.font={name:"Arial",size:11,bold:true}; cover.getRange("C4:C7").format.font={name:"Arial",size:11,bold:true}; cover.getRange("D5").setNumberFormat("yyyy-mm-dd");
cover.getRange("A9:F9").merge(); cover.getRange("A9").values=[["Record of Change"]]; cover.getRange("A9:F9").format={font:{name:"Arial",size:12,bold:true},horizontalAlignment:"center"};
cover.getRange("A10:F10").values=[["Effective Date","Version","Change Item","A/D/M","Change Description","Reference"]]; cover.getRange("A10:F10").format={fill:navy,font:{name:"Arial",size:11,bold:true,color:white},horizontalAlignment:"center",borders:border};
cover.getRange("A11:F11").values=[[new Date("2026-08-12"),"1.0","Initial creation","A","Full integration test design by system flow","Clinic Management System source code"]]; cover.getRange("A11:F11").format={font:{name:"Arial",size:10},wrapText:true,borders:border}; cover.getRange("A11").setNumberFormat("yyyy-mm-dd");
cover.getRange("A:F").format.columnWidth=23; cover.getRange("A2:F2").format.rowHeight=60; cover.getRange("A11:F11").format.rowHeight=42;

list.getRange("A2:F2").merge(); list.getRange("A2").values=[["INTEGRATION TEST FLOW LIST"]]; list.getRange("A2:F2").format={font:{name:"Arial",size:20,bold:true},horizontalAlignment:"center",verticalAlignment:"center",rowHeight:34};
list.getRange("A4:B7").values=[["Project Name","Clinic Management System"],["Project Code","CLINIC"],["Number of flows",15],["Number of test cases",90]]; list.getRange("A4:B7").format={font:{name:"Arial",size:11},borders:border}; list.getRange("A4:A7").format.font={name:"Arial",size:11,bold:true};
list.getRange("A10:F10").values=[["No","Flow Name","Flow Code","Sheet Name","Test Requirement","Pre-condition"]]; list.getRange("A10:F10").format={fill:navy,font:{name:"Arial",size:10,bold:true,color:white},horizontalAlignment:"center",verticalAlignment:"center",wrapText:true,borders:border};
list.getRange("A11:F25").values=flows.map(f=>[f.id,f.title,`IT${p2(f.id)}`,f.sheet,f.req,"Application, PostgreSQL, and Redis are running"]); list.getRange("A11:F25").format={font:{name:"Arial",size:10},verticalAlignment:"top",wrapText:true,borders:border}; list.getRange("A:A").format.columnWidth=8; list.getRange("B:B").format.columnWidth=30; list.getRange("C:C").format.columnWidth=13; list.getRange("D:D").format.columnWidth=24; list.getRange("E:F").format.columnWidth=38; list.getRange("A11:F25").format.rowHeight=38;

stats.getRange("A2:H2").merge(); stats.getRange("A2").values=[["TEST STATISTICS"]]; stats.getRange("A2:H2").format={font:{name:"Arial",size:20,bold:true},horizontalAlignment:"center",verticalAlignment:"center",rowHeight:34};
stats.getRange("A5:H5").values=[["No","Flow","Passed","Failed","Pending","N/A","Total","Completion"]]; stats.getRange("A5:H5").format={fill:navy,font:{name:"Arial",size:10,bold:true,color:white},horizontalAlignment:"center",borders:border};
stats.getRange("A6:B20").values=flows.map(f=>[f.id,`IT${p2(f.id)} - ${f.title}`]);
for(let r=6;r<=20;r++){const f=flows[r-6];stats.getRange(`C${r}:H${r}`).formulas=[[`='${f.sheet}'!B6`,`='${f.sheet}'!C6`,`='${f.sheet}'!D6`,`='${f.sheet}'!E6`,`=SUM(C${r}:F${r})`,`=IF(G${r}=0,0,(C${r}+D${r}+F${r})/G${r})`]];}
stats.getRange("A6:H20").format={font:{name:"Arial",size:10},wrapText:true,borders:border}; stats.getRange("H6:H20").setNumberFormat("0%"); stats.getRange("A:A").format.columnWidth=8; stats.getRange("B:B").format.columnWidth=42; stats.getRange("C:H").format.columnWidth=14;

for(const f of flows){
  const s=addSheet(f.sheet), cases=casesFor(f); s.freezePanes.freezeRows(10);
  s.getRange("A2").values=[["Feature"]]; s.getRange("B2:E2").merge(); s.getRange("B2").values=[[`IT${p2(f.id)} - ${f.title}`]];
  s.getRange("A3").values=[["Test requirement"]]; s.getRange("B3:E3").merge(); s.getRange("B3").values=[[f.req]];
  s.getRange("A4").values=[["Number of TCs"]]; s.getRange("B4:E4").merge(); s.getRange("B4").values=[[6]];
  s.getRange("A2:E4").format={font:{name:"Arial",size:10},verticalAlignment:"center",wrapText:true,borders:border}; s.getRange("A2:A4").format.font={name:"Arial",size:10,bold:true};
  s.getRange("A5:E5").values=[["Testing Round","Passed","Failed","Pending","N/A"]]; s.getRange("A5:E5").format={font:{name:"Arial",size:10,bold:true,italic:true},horizontalAlignment:"center",borders:border};
  s.getRange("A6:A8").values=[["Round 1"],["Round 2"],["Round 3"]]; s.getRange("A6:A8").format={font:{name:"Arial",size:10,bold:true,italic:true},horizontalAlignment:"center",borders:border};
  s.getRange("B6:E8").formulas=[
    ['=COUNTIF(F12:F19,"Passed")','=COUNTIF(F12:F19,"Failed")','=COUNTIF(F12:F19,"Pending")','=COUNTIF(F12:F19,"N/A")'],
    ['=COUNTIF(I12:I19,"Passed")','=COUNTIF(I12:I19,"Failed")','=COUNTIF(I12:I19,"Pending")','=COUNTIF(I12:I19,"N/A")'],
    ['=COUNTIF(L12:L19,"Passed")','=COUNTIF(L12:L19,"Failed")','=COUNTIF(L12:L19,"Pending")','=COUNTIF(L12:L19,"N/A")']
  ]; s.getRange("B6:E8").format={font:{name:"Arial",size:10},horizontalAlignment:"center",borders:border};
  s.getRange("A10:O10").values=[["Test Case ID","Test Case Description","Test Case Procedure","Expected Results","Pre-conditions","Round 1","Test date","Tester","Round 2","Test date","Tester","Round 3","Test date","Tester","Note"]]; s.getRange("A10:O10").format={fill:green,font:{name:"Arial",size:10,bold:true,color:white},horizontalAlignment:"center",verticalAlignment:"center",wrapText:true,borders:border};
  let row=11,index=0;
  for(const group of ["Successful flow","Validation and authorization","State and integration integrity"]){
    s.getRange(`A${row}:O${row}`).merge(); s.getRange(`A${row}`).values=[[group]]; s.getRange(`A${row}:O${row}`).format={fill:cyan,font:{name:"Arial",size:10,bold:true},verticalAlignment:"center",borders:border}; row++;
    for(let k=0;k<2;k++,index++,row++){
      const c=cases[index]; s.getRange(`A${row}:O${row}`).values=[[`IT${p2(f.id)}-${String(index+1).padStart(3,"0")}`,c.desc,c.proc,c.expected,c.pre,"Pending",null,null,"Pending",null,null,"Pending",null,null,`Flow IT${p2(f.id)}`]];
      s.getRange(`A${row}:O${row}`).format={font:{name:"Arial",size:9},verticalAlignment:"top",wrapText:true,borders:border}; s.getRange(`A${row}:O${row}`).format.rowHeight=86;
    }
  }
  s.getRange("F12:F19").dataValidation={rule:{type:"list",values:["Pending","Passed","Failed","N/A"]}}; s.getRange("I12:I19").dataValidation={rule:{type:"list",values:["Pending","Passed","Failed","N/A"]}}; s.getRange("L12:L19").dataValidation={rule:{type:"list",values:["Pending","Passed","Failed","N/A"]}};
  s.getRange("A:A").format.columnWidth=16; s.getRange("B:B").format.columnWidth=33; s.getRange("C:D").format.columnWidth=40; s.getRange("E:E").format.columnWidth=33; s.getRange("F:F").format.columnWidth=11; s.getRange("G:G").format.columnWidth=12; s.getRange("H:H").format.columnWidth=10; s.getRange("I:I").format.columnWidth=11; s.getRange("J:J").format.columnWidth=12; s.getRange("K:K").format.columnWidth=10; s.getRange("L:L").format.columnWidth=11; s.getRange("M:M").format.columnWidth=12; s.getRange("N:N").format.columnWidth=10; s.getRange("O:O").format.columnWidth=24;
}

const messages=addSheet("MessageList"); messages.getRange("A1:C1").values=[["Message Code","Message","Flow"]]; messages.getRange("A1:C1").format={fill:navy,font:{name:"Arial",size:10,bold:true,color:white},horizontalAlignment:"center",borders:border};
const messageRows=[]; for(const f of flows){messageRows.push([`IT${p2(f.id)}-INVALID`,`The submitted request data is invalid.`,`IT${p2(f.id)}`],[`IT${p2(f.id)}-STATE`,`The current business state does not allow this operation.`,`IT${p2(f.id)}`]);} messages.getRange("A2:C31").values=messageRows; messages.getRange("A2:C31").format={font:{name:"Arial",size:10},wrapText:true,borders:border}; messages.getRange("A:C").format.columnWidth=38;

await fs.mkdir(outputDir,{recursive:true}); await fs.mkdir(previewDir,{recursive:true});
const errors=await wb.inspect({kind:"match",searchTerm:"#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A",options:{useRegex:true,maxResults:300},maxChars:4000}); console.log(errors.ndjson);
const vietnamese=await wb.inspect({kind:"match",searchTerm:"Đăng|đăng|khám|Luồng|nghiệp vụ|mật khẩu|tài khoản|bệnh nhân|thanh toán",options:{useRegex:true,maxResults:100},maxChars:3000}); console.log(vietnamese.ndjson);
for(const f of flows){const img=await wb.render({sheetName:f.sheet,range:"A1:O19",scale:0.8,format:"png"}); await fs.writeFile(`${previewDir}/${f.sheet}.png`,new Uint8Array(await img.arrayBuffer()));}
for(const name of ["Cover","Test Cases","Test Statistics","MessageList"]){const img=await wb.render({sheetName:name,autoCrop:"all",scale:0.8,format:"png"}); await fs.writeFile(`${previewDir}/${name.replaceAll(" ","_")}.png`,new Uint8Array(await img.arrayBuffer()));}
const out=await SpreadsheetFile.exportXlsx(wb); await out.save(outputPath); console.log(outputPath);
