import os, runpy, shutil, zipfile
from xml.etree import ElementTree as ET

ns = runpy.run_path(r'D:\gitlap\doAnSummer2026\work\build_sample_ooxml.py')
load,save,q = ns['load'],ns['save'],ns['q']
clone_sheet,add_sheet = ns['clone_sheet'],ns['add_sheet']
prep_condition,prep_design,prep_feature = ns['prep_condition'],ns['prep_design'],ns['prep_feature']
set_text,set_num,set_formula,clear_range = ns['set_text'],ns['set_num'],ns['set_formula'],ns['clear_range']
RNS,PKG,CT,NS = ns['RNS'],ns['PKG'],ns['CT'],ns['NS']

SRC=r'D:\gitlap\doAnSummer2026\outputs\Report5_IntegrationTest_Clinic_Sample.xlsx'
OUT=r'D:\gitlap\doAnSummer2026\outputs\Report5_IntegrationTest_Clinic_Full.xlsx'
TMP=r'D:\gitlap\doAnSummer2026\work\full_unpack'

def C(name,valid,vtag,invalid,itag,vb,vbtag,ib,ibtag): return (name,valid,vtag,invalid,itag,vb,vbtag,ib,ibtag)
def T(n,desc,expected,tags): return (n,desc,expected,tags)
def F(i,id,desc,procedure,expected,pre,tags): return (f'IT{i:02}-{id:03}',desc,procedure,expected,pre,tags)

extras=[
dict(id=2,name='LoginToken',title='IT02 - Đăng nhập và refresh token',req='Account -> Authentication -> JWT access/refresh.',
 cond=[C('username','Account tồn tại','VP1','Không tồn tại/rỗng','IP1','Chuỗi hợp lệ','VB1','Null','IB1'),C('password','Đúng mật khẩu','VP2','Sai/rỗng','IP2','Độ dài hợp lệ','VB2','Rỗng','IB2'),C('account active','isActive=true','VP3','Tài khoản bị khóa','IP3','N/A','VB3','N/A','IB3'),C('refresh token','Token refresh hợp lệ, còn hạn','VP4','Access token/sai chữ ký/hết hạn','IP4','Ngay trước hết hạn','VB4','Sau hết hạn','IB4'),C('authorization','Bearer access token hợp lệ','VP5','Thiếu/sai token','IP5','N/A','VB5','Null','IB5'),C('role claim','Role/systemRole đúng account','VP6','Claim không khớp','IP6','N/A','VB6','N/A','IB6')],
 design=[T(1,'Đăng nhập đúng tài khoản active.','200; trả access/refresh token và thông tin role.','VP1,VP2,VP3,VP6'),T(2,'Đăng nhập sai password.','400; không cấp token.','IP2'),T(3,'Đăng nhập tài khoản bị khóa.','400; không cấp token.','IP3'),T(4,'Refresh bằng refresh token hợp lệ.','200; cấp bộ token mới.','VP4'),T(5,'Refresh bằng access token hoặc token hết hạn.','400; không cấp token.','IP4,IB4'),T(6,'Gọi /api/auth/me thiếu Bearer token.','401/403; không trả thông tin account.','IP5')],
 cases=[F(2,1,'Đăng nhập thành công','POST /api/auth/login với username/password đúng.','200; JWT có đúng accountId, role và systemRole.','Account active.','VP1,VP2,VP3,VP6'),F(2,2,'Sai mật khẩu','POST /api/auth/login với password sai.','400; không có token trong response.','Account tồn tại.','IP2'),F(2,3,'Tài khoản bị khóa','Khóa account rồi POST /api/auth/login.','400; không cấp token.','isActive=false.','IP3'),F(2,4,'Refresh token hợp lệ','POST /api/auth/refresh với refreshToken.','200; access/refresh mới hợp lệ.','Đã đăng nhập.','VP4'),F(2,5,'Sai loại token','POST /refresh bằng access token.','400; báo không phải refresh token.','Có access token.','IP4'),F(2,6,'Thiếu xác thực','GET /api/auth/me không Authorization.','401/403; không lộ dữ liệu account.','Không đăng nhập.','IP5')]),
dict(id=3,name='Profile',title='IT03 - Hồ sơ cá nhân',req='Account -> Profile -> lịch sử guest/BHXH.',
 cond=[C('profile/account','Profile thuộc account hiện tại','VP1','Không tồn tại/sai chủ','IP1','N/A','VB1','Null','IB1'),C('fullName','Không rỗng, dữ liệu hợp lệ','VP2','Rỗng/chỉ khoảng trắng','IP2','1 ký tự','VB2','0 ký tự','IB2'),C('phone/email','Đúng định dạng và chưa trùng','VP3','Sai định dạng/trùng','IP3','Chuỗi ngắn hợp lệ','VB3','Thiếu chữ số/domain','IB3'),C('dob','Không tương lai, tuổi hợp lệ','VP4','Tương lai/quá 150 tuổi','IP4','Hôm nay/150 tuổi','VB4','Ngày mai/151 tuổi','IB4'),C('gender','Enum hợp lệ','VP5','Giá trị ngoài enum','IP5','N/A','VB5','Null khi bắt buộc','IB5'),C('BHXH','Mã tồn tại hoặc không khai báo','VP6','Mã sai/không khớp','IP6','N/A','VB6','Rỗng không hợp lệ','IB6')],
 design=[T(1,'Xem hồ sơ của account hiện tại.','200; trả đúng Profile.','VP1'),T(2,'Cập nhật tên/SĐT/email hợp lệ.','200; Profile được cập nhật, Account không đổi.','VP2,VP3'),T(3,'Cập nhật ngày sinh tương lai.','400; không lưu.','IP4,IB4'),T(4,'Dùng email/SĐT đã thuộc profile khác.','409/400; không ghi đè.','IP3'),T(5,'Truy cập profile người khác không đủ quyền.','403; không lộ dữ liệu.','IP1'),T(6,'Kiểm tra BHXH hợp lệ qua service tích hợp.','200; trả quyền lợi/thông tin phù hợp.','VP6')],
 cases=[F(3,1,'Xem hồ sơ cá nhân','GET /api/v1/profiles/me bằng CUSTOMER.','200; profileId/accountId đúng token.','Customer đã đăng nhập.','VP1'),F(3,2,'Cập nhật hồ sơ hợp lệ','PUT /api/v1/profiles/me với fullName, phone, email.','200; DB cập nhật đúng một Profile.','Profile hiện hữu.','VP2,VP3'),F(3,3,'Ngày sinh tương lai','PUT /profiles/me với dob ngày mai.','400; DB giữ ngày sinh cũ.','Profile hiện hữu.','IP4,IB4'),F(3,4,'Email trùng','Cập nhật email đã thuộc Profile khác.','409/400; không thay đổi liên kết.','Có profile khác dùng email.','IP3'),F(3,5,'Sai quyền truy cập','CUSTOMER GET /profiles/{id} của người khác.','403; không trả dữ liệu nhạy cảm.','Hai customer khác nhau.','IP1'),F(3,6,'Tra cứu BHXH','GET /api/v1/bhxh/check với mã hợp lệ.','200; dữ liệu từ mock BHXH được ánh xạ đúng.','Mock BHXH chạy.','VP6')]),
dict(id=5,name='PaymentQueue',title='IT05 - Thanh toán và tạo hàng đợi',req='Invoice -> Transaction -> TestRequest/QueueTicket.',
 cond=[C('invoice','PENDING, tồn tại','VP1','Không tồn tại/PAID/CANCELLED','IP1','N/A','VB1','Null','IB1'),C('payment method','Enum hợp lệ','VP2','Ngoài enum/rỗng','IP2','N/A','VB2','Null','IB2'),C('amount','Đủ tổng hóa đơn','VP3','Thiếu/âm','IP3','Bằng tổng','VB3','Tổng-1','IB3'),C('insurance','Thông tin hợp lệ','VP4','Sai/không đủ điều kiện','IP4','Mức tối đa rule','VB4','Vượt rule','IB4'),C('invoice items','Có dịch vụ hợp lệ','VP5','Rỗng/service lỗi','IP5','1 item','VB5','0 item','IB5'),C('idempotency','Chưa thanh toán','VP6','Gọi pay lặp','IP6','N/A','VB6','N/A','IB6')],
 design=[T(1,'Thanh toán hóa đơn hợp lệ.','Invoice PAID; Transaction SUCCESS; sinh queue/request tương ứng.','VP1,VP2,VP3,VP5'),T(2,'Thanh toán thiếu tiền.','400; Invoice vẫn PENDING.','IP3,IB3'),T(3,'Thanh toán lại hóa đơn PAID.','409/400; không tạo transaction/queue trùng.','IP1,IP6'),T(4,'Áp dụng BHXH hợp lệ.','Tính covered/discount/total đúng rule.','VP4'),T(5,'Hủy invoice đã PAID.','409/400; giữ trạng thái PAID.','IP1'),T(6,'Thanh toán online thất bại.','Transaction FAILED; Invoice chưa PAID.','IP2')],
 cases=[F(5,1,'Thanh toán tiền mặt','POST /api/v1/invoices/{id}/pay.','Invoice PAID; Transaction SUCCESS; tạo bước hàng đợi cần thiết.','Invoice PENDING có item.','VP1,VP2,VP3,VP5'),F(5,2,'Số tiền thiếu','Pay với amount=total-1.','400; Invoice PENDING.','Invoice PENDING.','IP3,IB3'),F(5,3,'Thanh toán lặp','Gọi pay lần hai cho invoice PAID.','Không tạo Transaction/QueueTicket trùng.','Invoice PAID.','IP1,IP6'),F(5,4,'Áp dụng BHXH','POST /invoices/{id}/insurance.','Các khoản BHXH và patientPayable đúng rule.','Insurance hợp lệ.','VP4'),F(5,5,'Hủy invoice đã trả','POST /invoices/{id}/cancel.','409/400; không đổi PAID.','Invoice PAID.','IP1'),F(5,6,'PayOS thất bại','Tạo giao dịch PayOS rồi đánh dấu fail.','Transaction FAILED; Invoice chưa PAID.','Gateway trả lỗi.','IP2')]),
dict(id=6,name='QueueExam',title='IT06 - Hàng đợi và bắt đầu khám',req='QueueTicket -> CustomerVisit -> VitalSigns -> MedicalRecord.',
 cond=[C('queue status','WAITING/CALLED theo thao tác','VP1','DONE/SKIPPED/sai trạng thái','IP1','N/A','VB1','N/A','IB1'),C('department','Đúng khoa ticket','VP2','Sai/không tồn tại','IP2','N/A','VB2','Null','IB2'),C('staff role','Doctor/Nurse đúng quyền','VP3','Sai role','IP3','N/A','VB3','Null','IB3'),C('vital signs','Giá trị trong miền hợp lệ','VP4','Âm/vượt miền/thiếu liên kết','IP4','Giới hạn min/max','VB4','Ngoài giới hạn','IB4'),C('visit','CHECKED_IN/IN_PROGRESS','VP5','COMPLETED/CANCELLED','IP5','N/A','VB5','N/A','IB5'),C('concurrency','Ticket chưa bị staff khác nhận','VP6','Hai staff gọi/start đồng thời','IP6','N/A','VB6','N/A','IB6')],
 design=[T(1,'Gọi ticket WAITING.','Ticket -> CALLED; ghi calledAt.','VP1,VP2,VP3'),T(2,'Bắt đầu khám ticket CALLED.','Ticket/Visit IN_PROGRESS; tạo record liên quan.','VP1,VP5'),T(3,'Gọi lại ticket DONE.','400/409; không đổi trạng thái.','IP1'),T(4,'Nhập sinh hiệu hợp lệ.','Tạo VitalSigns gắn đúng Visit.','VP4'),T(5,'Nhập sinh hiệu ngoài miền.','400; không lưu.','IP4,IB4'),T(6,'Hai nhân viên thao tác cùng ticket.','Chỉ một thao tác thành công; không duplicate record.','IP6')],
 cases=[F(6,1,'Gọi bệnh nhân','POST /queue-tickets/{id}/call.','Queue WAITING -> CALLED; calledAt được ghi.','Ticket WAITING.','VP1,VP2,VP3'),F(6,2,'Bắt đầu khám','POST /queue-tickets/{id}/start-exam.','Queue và Visit IN_PROGRESS; dữ liệu khám sẵn sàng.','Ticket CALLED.','VP1,VP5'),F(6,3,'Ticket đã hoàn thành','Gọi /call cho ticket DONE.','400/409; trạng thái không đổi.','Ticket DONE.','IP1'),F(6,4,'Đo sinh hiệu','POST /api/v1/vital-signs với dữ liệu hợp lệ.','201; VitalSigns gắn đúng Visit.','Visit active.','VP4'),F(6,5,'Sinh hiệu không hợp lệ','POST nhiệt độ/huyết áp ngoài miền.','400; không lưu.','Visit active.','IP4,IB4'),F(6,6,'Gọi số đồng thời','Hai request /call cùng ticket.','Chỉ một thành công; không double-call.','Ticket WAITING.','IP6')]),
dict(id=7,name='Examination',title='IT07 - Khám, chẩn đoán và kê đơn',req='Visit -> MedicalRecord -> ICD10 -> Prescription.',
 cond=[C('record','IN_PROGRESS/DRAFT','VP1','COMPLETED/không tồn tại','IP1','N/A','VB1','Null','IB1'),C('doctor','Bác sĩ phụ trách','VP2','Sai role/sai bác sĩ','IP2','N/A','VB2','Null','IB2'),C('diagnosis','Không rỗng/ICD10 tồn tại','VP3','Rỗng/mã không tồn tại','IP3','1 mã','VB3','0 mã','IB3'),C('medicine','Thuốc tồn tại, active','VP4','Không tồn tại/inactive','IP4','1 item','VB4','0 item','IB4'),C('quantity/dose','Số dương','VP5','0/âm/sai định dạng','IP5','1','VB5','0','IB5'),C('record transition','IN_PROGRESS -> DRAFT/COMPLETED','VP6','Chuyển ngược COMPLETED','IP6','N/A','VB6','N/A','IB6')],
 design=[T(1,'Cập nhật hồ sơ khám hợp lệ.','Record lưu triệu chứng/chẩn đoán/ICD10.','VP1,VP2,VP3'),T(2,'Lưu nháp hồ sơ.','Status DRAFT; có thể sửa tiếp.','VP6'),T(3,'Kê đơn hợp lệ.','Tạo prescription items đúng thuốc/liều.','VP4,VP5'),T(4,'ICD10 không tồn tại.','404/400; không lưu chẩn đoán sai.','IP3'),T(5,'Số lượng thuốc bằng 0.','400; không tạo item.','IP5,IB5'),T(6,'Sửa hồ sơ COMPLETED.','409/400; không thay đổi.','IP1,IP6')],
 cases=[F(7,1,'Ghi nhận khám','PUT /api/doctor/examinations/{id}.','Record lưu triệu chứng, diagnosis và ICD10.','Doctor đúng record.','VP1,VP2,VP3'),F(7,2,'Lưu nháp','POST /medical-records/{id}/draft.','MedicalRecord DRAFT, dữ liệu giữ nguyên.','Record IN_PROGRESS.','VP6'),F(7,3,'Kê đơn','Cập nhật record với medicine và quantity hợp lệ.','PrescriptionItem được tạo đúng.','Medicine active.','VP4,VP5'),F(7,4,'Sai mã ICD10','Chọn ICD10 không tồn tại.','404/400; không liên kết mã sai.','Record editable.','IP3'),F(7,5,'Số lượng thuốc 0','Kê thuốc quantity=0.','400; không tạo item.','Medicine active.','IP5,IB5'),F(7,6,'Sửa hồ sơ hoàn tất','PUT record COMPLETED.','409/400; dữ liệu không đổi.','Record COMPLETED.','IP1,IP6')]),
dict(id=8,name='TestOrder',title='IT08 - Chỉ định cận lâm sàng',req='MedicalRecord -> TestRequest -> Department -> QueueTicket.',
 cond=[C('record','Record/Visit tồn tại','VP1','Không tồn tại/không Visit','IP1','N/A','VB1','Null','IB1'),C('service','Dịch vụ CLS tồn tại','VP2','Không tồn tại/inactive','IP2','1 service','VB2','0 service','IB2'),C('capability','Có khoa active hỗ trợ','VP3','Không có khoa/maintenance','IP3','1 khoa','VB3','0 khoa','IB3'),C('duplicate','Chưa chỉ định trong Visit','VP4','Đã có chưa CANCELLED','IP4','N/A','VB4','N/A','IB4'),C('batch services','Danh sách không rỗng, distinct','VP5','Rỗng/null','IP5','1 phần tử','VB5','0 phần tử','IB5'),C('queue sequence','Bước đầu WAITING, sau BLOCKED','VP6','Mở sai thứ tự','IP6','N/A','VB6','N/A','IB6')],
 design=[T(1,'Tạo một chỉ định hợp lệ.','Request PENDING; chọn khoa; tạo queue.','VP1,VP2,VP3,VP4'),T(2,'Tạo batch nhiều dịch vụ.','Mỗi dịch vụ unique có request; queue dùng chung theo khoa.','VP5'),T(3,'Dịch vụ không có khoa phù hợp.','404/400; không tạo request.','IP3'),T(4,'Chỉ định trùng trong Visit.','409; không duplicate.','IP4'),T(5,'Batch rỗng.','400 validation.','IP5,IB5'),T(6,'Nhiều khoa trong hành trình.','Chỉ bước đầu WAITING; bước sau BLOCKED.','VP6')],
 cases=[F(8,1,'Tạo chỉ định đơn','POST /api/v1/test-requests.','201; request PENDING và queue đúng khoa.','Record/Service hợp lệ.','VP1,VP2,VP3,VP4'),F(8,2,'Tạo batch','POST /test-requests/batch với nhiều serviceIds.','Tạo request distinct; dùng chung queue cùng khoa.','Record active.','VP5'),F(8,3,'Không có khoa phù hợp','Chỉ định service thiếu capability/khoa active.','404/400; không tạo request.','Service cấu hình lỗi.','IP3'),F(8,4,'Chỉ định trùng','POST cùng service trong Visit.','409; không duplicate.','Request cũ chưa hủy.','IP4'),F(8,5,'Batch rỗng','POST serviceIds=[].','400 validation.','Record active.','IP5,IB5'),F(8,6,'Tuần tự nhiều khoa','Tạo request ở hai khoa.','Queue đầu WAITING; queue sau BLOCKED.','Visit chưa có bước active khác.','VP6')]),
dict(id=10,name='CompleteFollowup',title='IT10 - Hoàn tất khám và tái khám',req='MedicalRecord -> Visit/Queue -> Follow-up Appointment.',
 cond=[C('record status','IN_PROGRESS/DRAFT','VP1','COMPLETED','IP1','N/A','VB1','N/A','IB1'),C('test requests','Tất cả COMPLETED hoặc không có','VP2','Còn PENDING/IN_PROGRESS','IP2','0 incomplete','VB2','1 incomplete','IB2'),C('follow-up date','Tương lai','VP3','Quá khứ','IP3','Ngày mai','VB3','Hôm qua','IB3'),C('service','Dịch vụ tái khám tồn tại','VP4','Không tồn tại','IP4','1 service','VB4','0 service','IB4'),C('queue/visit','Đang IN_PROGRESS','VP5','DONE/CANCELLED','IP5','N/A','VB5','N/A','IB5'),C('feedback/rating','Trong miền cho phép','VP6','Ngoài miền/gửi trùng','IP6','Min/max','VB6','Min-1/max+1','IB6')],
 design=[T(1,'Hoàn tất hồ sơ đủ điều kiện.','Record/Visit/Queue COMPLETED/DONE.','VP1,VP2,VP5'),T(2,'Còn xét nghiệm chưa xong.','400; hồ sơ chưa hoàn tất.','IP2,IB2'),T(3,'Tạo lịch tái khám hợp lệ.','Appointment PENDING liên kết record/service.','VP3,VP4'),T(4,'Ngày tái khám quá khứ.','400; không tạo appointment.','IP3'),T(5,'Hoàn tất lại record COMPLETED.','409/400; không lặp side effect.','IP1'),T(6,'Bệnh nhân đánh giá hợp lệ.','Lưu rating/feedback đúng record.','VP6')],
 cases=[F(10,1,'Hoàn tất khám','POST /medical-records/{id}/complete.','Record COMPLETED; Visit COMPLETED; Queue DONE.','Không còn test incomplete.','VP1,VP2,VP5'),F(10,2,'Còn xét nghiệm','Complete khi có TestRequest PENDING.','400; record giữ IN_PROGRESS.','Có request chưa xong.','IP2,IB2'),F(10,3,'Tạo tái khám','POST /medical-records/{id}/follow-up-appointment.','Appointment PENDING liên kết đúng customer/service.','Ngày tương lai.','VP3,VP4'),F(10,4,'Tái khám quá khứ','Tạo follow-up ngày hôm qua.','400; không tạo appointment.','Record tồn tại.','IP3'),F(10,5,'Hoàn tất lặp','Complete record đã COMPLETED.','Không tạo side effect trùng.','Record COMPLETED.','IP1'),F(10,6,'Đánh giá lượt khám','POST /medical-records/{id}/rate với rating hợp lệ.','Rating lưu đúng customer/record.','Customer sở hữu record.','VP6')]),
dict(id=11,name='InsuranceTxn',title='IT11 - BHXH và giao dịch',req='Insurance/BHXH -> Invoice -> Transaction -> Payment history.',
 cond=[C('insurance code','Tồn tại/active','VP1','Không tồn tại/inactive','IP1','Đúng độ dài','VB1','Sai độ dài','IB1'),C('coverage rule','Dịch vụ thuộc rule','VP2','Không thuộc/quá hạn','IP2','Đúng trần','VB2','Vượt trần','IB2'),C('invoice','PENDING đúng customer','VP3','Sai customer/PAID','IP3','N/A','VB3','Null','IB3'),C('transaction','PENDING','VP4','SUCCESS/FAILED xử lý lại','IP4','N/A','VB4','N/A','IB4'),C('payment method','CASH/PayOS hợp lệ','VP5','Ngoài enum','IP5','N/A','VB5','Null','IB5'),C('history access','Customer sở hữu invoice','VP6','Customer khác','IP6','N/A','VB6','N/A','IB6')],
 design=[T(1,'Kiểm tra BHXH hợp lệ.','Trả thông tin và coverage.','VP1,VP2'),T(2,'Áp dụng BHXH vào invoice.','Tính covered/patient payable đúng.','VP2,VP3'),T(3,'BHXH inactive/sai mã.','404/400; không áp dụng.','IP1'),T(4,'Confirm transaction PENDING.','Transaction SUCCESS; Invoice PAID.','VP4,VP5'),T(5,'Confirm lại SUCCESS.','Không side effect trùng.','IP4'),T(6,'Customer xem invoice người khác.','403/404; không lộ lịch sử.','IP6')],
 cases=[F(11,1,'Tra BHXH','GET /api/v1/bhxh/check.','200; dữ liệu coverage đúng.','Mock BHXH active.','VP1,VP2'),F(11,2,'Áp BHXH hóa đơn','POST /invoices/{id}/insurance.','Tổng BHXH/bệnh nhân trả đúng rule.','Invoice PENDING đúng customer.','VP2,VP3'),F(11,3,'Mã BHXH sai','Check mã không tồn tại.','404/400; không cập nhật invoice.','Mã invalid.','IP1'),F(11,4,'Xác nhận giao dịch','POST /transactions/{id}/confirm.','Transaction SUCCESS; Invoice PAID.','Transaction PENDING.','VP4,VP5'),F(11,5,'Xác nhận lặp','Confirm transaction SUCCESS.','Không tạo side effect trùng.','Transaction SUCCESS.','IP4'),F(11,6,'Sai chủ hóa đơn','GET /api/patient/payments/{invoiceId} người khác.','403/404; không trả dữ liệu.','Hai customer.','IP6')]),
dict(id=12,name='StaffSchedule',title='IT12 - Nhân sự, lịch và chấm công',req='Staff -> Capability -> Schedule -> Attendance/Adjustment.',
 cond=[C('staff','Tồn tại, active','VP1','Không tồn tại/bị khóa','IP1','N/A','VB1','Null','IB1'),C('systemRole','Role hợp lệ','VP2','Role không phù hợp','IP2','N/A','VB2','Null','IB2'),C('schedule time','Không chồng lịch','VP3','Chồng ca','IP3','Sát đầu/cuối ca','VB3','Chồng 1 phút','IB3'),C('capability','Đúng chuyên môn/khoa','VP4','Không đủ capability','IP4','1 capability','VB4','0 capability','IB4'),C('attendance token','Token kiosk hợp lệ/còn hạn','VP5','Sai/hết hạn/dùng lại','IP5','Ngay trước hết hạn','VB5','Sau hết hạn','IB5'),C('adjustment','PENDING trước review','VP6','Đã review/sai owner','IP6','N/A','VB6','N/A','IB6')],
 design=[T(1,'Tạo lịch nhân viên hợp lệ.','Schedule active, đúng staff/shift.','VP1,VP2,VP3,VP4'),T(2,'Tạo lịch chồng ca.','409/400; không lưu.','IP3,IB3'),T(3,'Nhân viên thiếu capability.','400; không assign.','IP4'),T(4,'Quét chấm công hợp lệ.','Attendance ghi check-in/out.','VP5'),T(5,'Token hết hạn/dùng lại.','400; không ghi trùng.','IP5,IB5'),T(6,'Manager duyệt điều chỉnh.','Adjustment chuyển APPROVED/REJECTED.','VP6')],
 cases=[F(12,1,'Xếp lịch hợp lệ','POST /api/v1/schedules.','201; Schedule đúng staff/shift/khoa.','Staff active, capability phù hợp.','VP1,VP2,VP3,VP4'),F(12,2,'Lịch chồng ca','Tạo ca chồng lịch hiện có 1 phút.','409/400; không lưu.','Có schedule cũ.','IP3,IB3'),F(12,3,'Thiếu capability','Assign staff vào dịch vụ không đủ capability.','400; không tạo schedule.','Staff active.','IP4'),F(12,4,'Quét chấm công','POST /api/v1/attendance/scan token hợp lệ.','Attendance ghi đúng staff/time.','Token kiosk còn hạn.','VP5'),F(12,5,'Token hết hạn','Scan token hết hạn/dùng lại.','400; không duplicate attendance.','Token invalid.','IP5,IB5'),F(12,6,'Duyệt điều chỉnh','PUT /attendance/adjustments/{id}/review.','Status APPROVED/REJECTED; audit đúng manager.','Adjustment PENDING.','VP6')]),
dict(id=13,name='AdminCatalog',title='IT13 - Quản trị danh mục hệ thống',req='Department/Service/Category/Specialization/Staff/Capability.',
 cond=[C('admin role','ADMIN/CLINIC_MANAGER đúng API','VP1','Sai role','IP1','N/A','VB1','Null','IB1'),C('code/name','Không rỗng, unique','VP2','Rỗng/trùng','IP2','Min/max length','VB2','Ngoài length','IB2'),C('department status','ACTIVE/INACTIVE/MAINTENANCE hợp lệ','VP3','Ngoài enum','IP3','N/A','VB3','Null','IB3'),C('service price','>=0','VP4','Âm/sai kiểu','IP4','0','VB4','-1','IB4'),C('dependency','Không có dữ liệu phụ thuộc khi xóa','VP5','Đang được sử dụng','IP5','0 dependency','VB5','1 dependency','IB5'),C('capability mapping','Service/department/staff tồn tại','VP6','Một đầu không tồn tại','IP6','1 mapping','VB6','0 mapping','IB6')],
 design=[T(1,'Tạo khoa/dịch vụ hợp lệ.','201; dữ liệu active và unique.','VP1,VP2,VP3,VP4'),T(2,'Tạo code trùng.','409; không duplicate.','IP2'),T(3,'Giá dịch vụ âm.','400; không lưu.','IP4,IB4'),T(4,'Publish/deactivate dịch vụ.','Status chuyển đúng.','VP3'),T(5,'Xóa danh mục đang được dùng.','409/400; giữ dữ liệu.','IP5,IB5'),T(6,'Gán capability hợp lệ.','Mapping được lưu và dùng khi chọn khoa.','VP6')],
 cases=[F(13,1,'Tạo khoa/dịch vụ','POST /departments và /medical-services hợp lệ.','201; code unique, status đúng.','ADMIN token.','VP1,VP2,VP3,VP4'),F(13,2,'Code trùng','POST entity có code đã tồn tại.','409; không duplicate.','Có entity cùng code.','IP2'),F(13,3,'Giá âm','POST medical-service price=-1.','400; không lưu.','ADMIN token.','IP4,IB4'),F(13,4,'Đổi trạng thái dịch vụ','PATCH /medical-services/{id}/publish/deactivate.','Status chuyển đúng và API available phản ánh.','Service tồn tại.','VP3'),F(13,5,'Xóa đang được dùng','DELETE department/service có dependency.','409/400; dữ liệu giữ nguyên.','Có appointment/request liên kết.','IP5,IB5'),F(13,6,'Gán capability','POST /service-capabilities và gán staff/khoa.','Mapping lưu đúng, được chọn khi tạo request.','Các entity tồn tại.','VP6')]),
dict(id=14,name='NotifyChat',title='IT14 - Thông báo và hỗ trợ chat',req='Account/Profile -> Notification -> ChatSession/WebSocket.',
 cond=[C('recipient','Account/Profile tồn tại','VP1','Không tồn tại','IP1','N/A','VB1','Null','IB1'),C('channel','Enum hợp lệ','VP2','Ngoài enum','IP2','N/A','VB2','Null','IB2'),C('notification status','PENDING/SENT/READ','VP3','Chuyển trạng thái sai','IP3','N/A','VB3','N/A','IB3'),C('chat session','ACTIVE','VP4','CLOSED/không tồn tại','IP4','N/A','VB4','Null','IB4'),C('sender role','Customer/guest/receptionist đúng endpoint','VP5','Giả mạo role','IP5','N/A','VB5','Null','IB5'),C('message','Không rỗng, trong giới hạn','VP6','Rỗng/quá dài','IP6','1 ký tự','VB6','0 ký tự','IB6')],
 design=[T(1,'Tạo và gửi notification.','Status SENT, đúng recipient/channel.','VP1,VP2,VP3'),T(2,'Đánh dấu đã đọc.','READ; unread-count giảm.','VP3'),T(3,'Tạo chat session.','ACTIVE; gắn customer/guest.','VP4'),T(4,'Gửi message đúng role.','Message lưu và phát WebSocket.','VP5,VP6'),T(5,'Gửi vào session CLOSED.','409/400; không lưu.','IP4'),T(6,'Message rỗng.','400 validation.','IP6,IB6')],
 cases=[F(14,1,'Gửi thông báo','POST /notifications rồi /{id}/send.','Notification SENT đúng recipient/channel.','Recipient tồn tại.','VP1,VP2,VP3'),F(14,2,'Đọc thông báo','POST /notifications/{id}/mark-read.','Status READ; unread-count giảm 1.','Notification SENT.','VP3'),F(14,3,'Mở phiên chat','POST /api/v1/chat/session.','ChatSession ACTIVE gắn customer.','Customer authenticated.','VP4'),F(14,4,'Gửi tin nhắn','POST /chat/{sessionId}/messages/customer.','Message lưu và broadcast.','Session ACTIVE.','VP5,VP6'),F(14,5,'Phiên đã đóng','Gửi message vào session CLOSED.','409/400; không lưu message.','Session CLOSED.','IP4'),F(14,6,'Tin nhắn rỗng','POST message rỗng.','400; không tạo message.','Session ACTIVE.','IP6,IB6')]),
dict(id=15,name='JourneyReport',title='IT15 - Hành trình, báo cáo và phản hồi',req='Visit/Queue/Record/Invoice -> Journey/Report/Feedback/Audit.',
 cond=[C('visit','Tồn tại và thuộc customer','VP1','Không tồn tại/sai chủ','IP1','N/A','VB1','Null','IB1'),C('journey step','Bước hiện tại hợp lệ','VP2','Advance sai thứ tự','IP2','Bước đầu/cuối','VB2','Ngoài chuỗi','IB2'),C('report range','from<=to','VP3','from>to/sai format','IP3','Cùng ngày','VB3','Đảo 1 ngày','IB3'),C('manager role','CLINIC_MANAGER/ADMIN','VP4','Sai role','IP4','N/A','VB4','Null','IB4'),C('rating','Trong miền','VP5','Ngoài miền/gửi trùng','IP5','Min/max','VB5','Min-1/max+1','IB5'),C('audit entity','Entity/action tồn tại','VP6','Sai entity/id','IP6','N/A','VB6','Null','IB6')],
 design=[T(1,'Xem hành trình bệnh nhân.','Trả đúng thứ tự queue/record/test.','VP1,VP2'),T(2,'Advance bước hiện tại.','Bước kế tiếp được activate.','VP2'),T(3,'Advance sai thứ tự.','409/400; không mở bước sai.','IP2'),T(4,'Xem dashboard theo khoảng ngày.','Số liệu khớp Visit/Invoice/Service.','VP3,VP4'),T(5,'Customer gửi rating hợp lệ.','Rating/Feedback lưu đúng record.','VP5'),T(6,'Truy vấn audit log.','Trả snapshot/action đúng entity.','VP6')],
 cases=[F(15,1,'Xem hành trình','GET /api/v1/patient-journeys/{visitId}.','Danh sách bước đúng trạng thái/thứ tự.','Visit tồn tại.','VP1,VP2'),F(15,2,'Chuyển bước','POST /patient-journeys/{visitId}/advance.','Bước sau BLOCKED -> WAITING.','Bước hiện tại DONE.','VP2'),F(15,3,'Sai thứ tự','Advance khi bước hiện tại chưa DONE.','409/400; không mở bước sau.','Có active step.','IP2'),F(15,4,'Dashboard','GET /api/v1/reports/dashboard với date range.','KPI khớp dữ liệu Visit/Invoice.','Manager token.','VP3,VP4'),F(15,5,'Phản hồi','POST /medical-history/{recordId}/feedback.','Feedback gắn đúng customer/record.','Record COMPLETED.','VP5'),F(15,6,'Audit log','GET /api/v1/audit-logs/by-entity.','Trả action/snapshot đúng thứ tự.','ADMIN/MANAGER token.','VP6')])]

if os.path.exists(TMP): shutil.rmtree(TMP)
os.makedirs(TMP)
with zipfile.ZipFile(SRC) as z:z.extractall(TMP)
wbp=os.path.join(TMP,'xl','workbook.xml');relp=os.path.join(TMP,'xl','_rels','workbook.xml.rels');ctp=os.path.join(TMP,'[Content_Types].xml')
wbt=load(wbp);wbr=wbt.getroot();relt=load(relp);relroot=relt.getroot();ctt=load(ctp);ctroot=ctt.getroot()
# Remove stale/broken sample defined names.
dn=wbr.find(q('definedNames'))
if dn is not None:wbr.remove(dn)
base_ca=os.path.join(TMP,'xl','worksheets','sheet5.xml');base_td=os.path.join(TMP,'xl','worksheets','sheet6.xml');base_f=os.path.join(TMP,'xl','worksheets','sheet7.xml')
sheet_no=14;rel_no=30
for flow in extras:
    names=[f"CA-IT{flow['id']:02}-{flow['name']}",f"TD-IT{flow['id']:02}-{flow['name']}",f"IT{flow['id']:02}-{flow['name']}"]
    bases=[base_ca,base_td,base_f]
    for nm,base in zip(names,bases):
        file=f'sheet{sheet_no}.xml';clone_sheet(base,os.path.join(TMP,'xl','worksheets',file));add_sheet(wbr,relroot,ctroot,nm[:31],file,sheet_no,f'rId{rel_no}');sheet_no+=1;rel_no+=1
ET.register_namespace('',NS);save(wbt,wbp);ET.register_namespace('',PKG);save(relt,relp);ET.register_namespace('',CT);save(ctt,ctp);ET.register_namespace('',NS);ET.register_namespace('r',RNS)

sheet_no=14
for flow in extras:
    prep_condition(os.path.join(TMP,'xl','worksheets',f'sheet{sheet_no}.xml'),flow['cond']);sheet_no+=1
    prep_design(os.path.join(TMP,'xl','worksheets',f'sheet{sheet_no}.xml'),flow['design']);sheet_no+=1
    prep_feature(os.path.join(TMP,'xl','worksheets',f'sheet{sheet_no}.xml'),flow['title'],flow['req'],[('Luồng hợp lệ',2),('Validation nghiệp vụ',2),('Quyền/trạng thái biên',2)],flow['cases']);sheet_no+=1

allmods=[(1,'Register','Đăng ký và OTP'),(2,'LoginToken','Đăng nhập và token'),(3,'Profile','Hồ sơ cá nhân'),(4,'Appointment','Đặt lịch và check-in'),(5,'PaymentQueue','Thanh toán và queue'),(6,'QueueExam','Hàng đợi và bắt đầu khám'),(7,'Examination','Khám và kê đơn'),(8,'TestOrder','Chỉ định CLS'),(9,'LabResult','Trả kết quả CLS'),(10,'CompleteFollowup','Hoàn tất và tái khám'),(11,'InsuranceTxn','BHXH và giao dịch'),(12,'StaffSchedule','Nhân sự và chấm công'),(13,'AdminCatalog','Quản trị danh mục'),(14,'NotifyChat','Thông báo và chat'),(15,'JourneyReport','Hành trình và báo cáo')]
# Existing names use these exact forms.
feature_names={1:'IT01-Register',4:'IT04-Appointment',9:'IT09-LabResult'}
for i,n,_ in allmods:feature_names.setdefault(i,f'IT{i:02}-{n}'[:31])

lstp=os.path.join(TMP,'xl','worksheets','sheet2.xml');t=load(lstp);r=t.getroot();clear_range(r,9,40,2,6)
for rn,(i,n,label) in enumerate(allmods,9):
    vals=(i,f'IT{i:02} - {label}',feature_names[i],label,'Theo pre-condition của Feature')
    set_num(r,f'B{rn}',i,19)
    for col,v in zip('CDEF',vals[1:]):set_text(r,f'{col}{rn}',v,20 if col=='C' else 94 if col=='D' else 21)
links=r.find(q('hyperlinks'))
if links is None:links=ET.SubElement(r,q('hyperlinks'))
else:links.clear()
for rn,(i,_,_) in enumerate(allmods,9):ET.SubElement(links,q('hyperlink'),{'ref':f'D{rn}','location':f"'{feature_names[i]}'!A1",'display':feature_names[i]})
dim=r.find(q('dimension'));dim.set('ref','B1:F23');save(t,lstp)

statp=os.path.join(TMP,'xl','worksheets','sheet3.xml');t=load(statp);r=t.getroot();clear_range(r,11,40,2,8)
template=ns['get_row'](r,11)
for idx,(i,_,_) in enumerate(allmods,11):
    ns['get_row'](r,idx,template);set_num(r,f'B{idx}',i,62);set_formula(r,f'C{idx}',f"'{feature_names[i]}'!B2",0,63)
    for col,src in zip('DEFGH','BCDEB'):set_formula(r,f'{col}{idx}',f"'{feature_names[i]}'!{src}{6 if col!='H' else 4}",6 if col in ('F','H') else 0,64)
subtotal=27
set_text(r,f'C{subtotal}','Sub total',68)
for col in 'DEFGH':set_formula(r,f'{col}{subtotal}',f'SUM({col}11:{col}25)',90 if col in ('F','H') else 0,69)
set_text(r,'C29','Test coverage',74);set_formula(r,'E29',f'IFERROR((D{subtotal}+E{subtotal})*100/(H{subtotal}-G{subtotal}),0)',0,75);set_text(r,'F29','%',1)
set_text(r,'C30','Test successful coverage',74);set_formula(r,'E30',f'IFERROR(D{subtotal}*100/(H{subtotal}-G{subtotal}),0)',0,75);set_text(r,'F30','%',1)
dim=r.find(q('dimension'));dim.set('ref','A1:H30');save(t,statp)

msgp=os.path.join(TMP,'xl','worksheets','sheet8.xml');t=load(msgp);r=t.getroot();clear_range(r,2,88,1,3)
rn=2
for i,_,label in allmods:
    for code,desc in [('INVALID',f'Dữ liệu {label} không hợp lệ'),('STATE',f'Trạng thái {label} không cho phép thao tác')]:
        set_text(r,f'A{rn}',f'IT{i:02}-{code}',154);set_text(r,f'B{rn}',desc,154);set_text(r,f'C{rn}',f'IT{i:02}',154);rn+=1
save(t,msgp)

with zipfile.ZipFile(OUT,'w',zipfile.ZIP_DEFLATED) as z:
    for root,_,files in os.walk(TMP):
        for f in files:
            p=os.path.join(root,f);z.write(p,os.path.relpath(p,TMP))
print(OUT)
